### ISSUE TITLE
Nokogiri removal request

### ISSUE THREAD

**Issue by lyndsey-ferguson** [dyang/merge_junit_report#2]
Is it possible to update this plugin to no longer use `nokogiri` and instead use something that does not require manual installation? What I mean is that when ever I update gems, I always have to `brew unlink xz` and call `gem install nokogiri-version-number` and then `brew link xz`. Its a pain.

I transitioned `fastlane-plugin-setup_fragile_tests_for_rescan` to use `REXML` and it seems to work nicely; it is included in Ruby.

**Comment by dyang** [comment]
@lyndsey-ferguson I've come across this issue a few times as well. Sounds like a great plan. I'll look into it.

**Comment by lyndsey-ferguson** [comment]
👍 Let me know if you need any help. I have had to convert a number of tests to use REXML

**Comment by dyang** [comment]
I haven't used REXML yet, so any help will be appreciated. Do you mind making a PR on this? :)

**Comment by lyndsey-ferguson** [comment]
I was hoping you would do it 🤞 It is almost the same and my brain is a little fried from fixing it in several different codebases. I can help if you want to give it a shot.

Take a look at this: https://github.com/lyndsey-ferguson/fastlane_plugins/blob/master/fastlane-plugin-setup_fragile_tests_for_rescan/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb

The main thing that tripped me up is the xpath apis. You have to use `REXML::XPath.match(xmldoc_or_element, '//path/to/element')`

**Comment by dyang** [comment]
Thanks for the tip! I'll give this a shot later this week.

**Comment by lyndsey-ferguson** [comment]
Any luck yet?

**Comment by dyang** [comment]
Hi, sorry not yet. Kids are sick plus other things. Might take a few more days to get around to this. :(

**Comment by dyang** [comment]
Just pushed a new release. Let me know how it works. :)

**Comment by lyndsey-ferguson** [comment]
Thank you so much, I will enable this and let you know!

**Comment by dyang** [comment]
Fixed in v0.5.0.
