### ISSUE TITLE
Move merge  functionality to separate gem

### ISSUE THREAD

**Issue by curpeng** [dyang/merge_junit_report#4]
Right now this repository is useful only for `fastlane` users. Can you move merging functionality to separate gem and add this new gem as a dependency to the current project, please?

**Comment by dyang** [comment]
Thanks for the feedback. So far I don't have a plan for this yet. Can you elaborate a bit on your use case?

**Comment by curpeng** [comment]
@dyang I split(by lines count) tests into several groups and run them in parallel. When test build is finished I have several junit reports, I need to merge them into one report to be able to split tests by their time execution.

**Comment by dyang** [comment]
Good to know your use case. I'll consider this but at the moment I can't guarantee anything. Sorry.
